ViewComponents/Models/CategoryListViewModel.cs
using Microsoft.Extensions.Primitives;
using System.Collections.Generic;
using ViewComponents.Entites;

namespace ViewComponents
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public StringValues CategoryId { get; internal set; }
    }
}

ViewComponents/Models/NorthwindDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponents.Entites;

namespace ViewComponents.Models
{
    public class NorthwindDbContext:DbContext
    {
        public NorthwindDbContext(DbContextOptions<NorthwindDbContext> options):base(options)
        {

        }
        public DbSet<Product> Products { get; set; }
        public DbSet<Category> Categories { get; set; }

    }
}

ViewComponents/Models/ProductListViewModel.cs
using Microsoft.Extensions.Primitives;
using System.Collections.Generic;
using ViewComponents.Entites;

namespace ViewComponents
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
    }
}

ViewComponents/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponents.Entites;
using ViewComponents.Models;

namespace ViewComponents.Controllers
{
    public class HomeController : Controller
    {
        public NorthwindDbContext _context;
        public HomeController(NorthwindDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var productList = new List<Product>();
            var categoryId = HttpContext.Request.Query["categoryId"];
            if (string.IsNullOrEmpty(categoryId))
            {
                productList = _context.Products.ToList();
            }
            else
            {
                productList = _context.Products.Where(p => p.CategoryId == int.Parse(categoryId)).ToList();
            }

            var productListViewModel = new ProductListViewModel
            {
                Products = productList,
            };
            return View(productListViewModel);
        }
    }
}

ViewComponents/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponents.Models;

namespace ViewComponents.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        public NorthwindDbContext _context;
        public CategoryListViewComponent(NorthwindDbContext context)
        {
            _context = context;
        }
        public ViewViewComponentResult Invoke()
        {

            var categoryId =HttpContext.Request.Query["categoryId"];
            
            var model = new CategoryListViewModel
            {
                Categories = _context.Categories.ToList(),
                CategoryId=categoryId
            };
            return View(model);
        }
    }
}

ViewComponents/Views/Home/Index.cshtml
@model ViewComponents.ProductListViewModel

<h2 class="text-center text-danger">Product List</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>ProductId</td>
            <td>ProductName</td>
            <td>CategoryId</td>
            <td>QuantityPerUnit</td>
            <td>UnitPrice</td>
            <td>UnitsInStock</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
        <tr>
            <td>@item.ProductId</td>
            <td>@item.ProductName</td>
            <td>@item.CategoryId</td>
            <td>@item.QuantityPerUnit</td>
            <td>@item.UnitPrice</td>
            <td>@item.UnitsInStock</td>
        </tr>
        }
    </tbody>
</table>

ViewComponents/Views/Shared/Components/CategoryList/Default.cshtml
@model ViewComponents.CategoryListViewModel


<h3 class="text-center text-warning">Category List</h3>

<ul class="list-group ">
    <li class="list-group-item bg-danger" ><a class="text-decoration-none text-white" href="/home/index">All Products</a> </li>
    @foreach (var item in Model.Categories)
    {
        if (Model.CategoryId == item.CategoryId.ToString())
        {
            <li class="list-group-item active"><a class=" text-decoration-none text-white" href="/home/index?categoryId=@item.CategoryId">@item.CategoryName</a> </li>
        }
        else
        {
            <li class="list-group-item  bg-danger "><a class=" text-decoration-none  text-white" href="/home/index?categoryId=@item.CategoryId">@item.CategoryName</a> </li>
        }
    }
</ul>

ViewComponents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row mt-5">
            <div class="col-2 bg-danger">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <div class="col-10 bg-warning">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>